
import React from 'react';
import { APP_NAME } from '../constants';
import { Logo } from './Logo';

export type LegalSection = 'privacy' | 'terms' | 'cookies';

interface LegalPageProps {
  section: LegalSection;
  onBack: () => void;
}

export const LegalPage: React.FC<LegalPageProps> = ({ section, onBack }) => {
  
  const renderContent = () => {
    switch (section) {
      case 'privacy':
        return (
          <div className="space-y-6">
            <h1 className="text-3xl font-bold text-gray-900 dark:text-white">Privacy Policy</h1>
            <p className="text-gray-600 dark:text-gray-300">Last updated: May 2025</p>
            
            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white">1. Introduction</h2>
              <p className="text-gray-600 dark:text-gray-300">
                {APP_NAME} ("we," "our," or "us") respects your privacy and is committed to protecting your personal data. 
                This privacy policy will inform you as to how we look after your personal data when you use our health analysis application.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white">2. Data We Collect</h2>
              <p className="text-gray-600 dark:text-gray-300">
                We may collect, use, store and transfer different kinds of personal data about you which we have grouped together follows:
              </p>
              <ul className="list-disc pl-5 text-gray-600 dark:text-gray-300 space-y-1">
                <li><strong>Identity Data:</strong> Email address, user ID.</li>
                <li><strong>Health Data:</strong> Symptoms, images, audio recordings, and documents you voluntarily upload for analysis.</li>
                <li><strong>Technical Data:</strong> Internet protocol (IP) address, browser type and version, time zone setting.</li>
              </ul>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white">3. How We Use Your Data</h2>
              <p className="text-gray-600 dark:text-gray-300">
                We use your data exclusively to:
              </p>
              <ul className="list-disc pl-5 text-gray-600 dark:text-gray-300 space-y-1">
                <li>Provide the AI-powered health analysis services.</li>
                <li>Manage your account and subscription.</li>
                <li>Improve our algorithms (only using anonymized, non-identifiable data).</li>
              </ul>
              <p className="text-gray-600 dark:text-gray-300 mt-2">
                <strong>We do not sell your personal health data to third parties.</strong>
              </p>
            </section>

             <section className="space-y-3">
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white">4. Data Security</h2>
              <p className="text-gray-600 dark:text-gray-300">
                We have put in place appropriate security measures (including 256-bit encryption) to prevent your personal data from being accidentally lost, used, or accessed in an unauthorized way.
              </p>
            </section>
          </div>
        );
      case 'terms':
        return (
          <div className="space-y-6">
            <h1 className="text-3xl font-bold text-gray-900 dark:text-white">Terms of Service</h1>
            <p className="text-gray-600 dark:text-gray-300">Last updated: May 2025</p>

            <div className="p-4 bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-700 rounded-lg">
               <p className="text-yellow-800 dark:text-yellow-200 font-medium">
                 CRITICAL DISCLAIMER: {APP_NAME} IS NOT A DOCTOR.
               </p>
            </div>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white">1. Educational Use Only</h2>
              <p className="text-gray-600 dark:text-gray-300">
                The content generated by {APP_NAME} is for informational and educational purposes only. It is not intended to be a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white">2. User Accounts</h2>
              <p className="text-gray-600 dark:text-gray-300">
                You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white">3. Acceptable Use</h2>
              <p className="text-gray-600 dark:text-gray-300">
                You agree not to use the Service to upload illegal content, harass others, or attempt to bypass security measures.
              </p>
            </section>
          </div>
        );
      case 'cookies':
        return (
          <div className="space-y-6">
            <h1 className="text-3xl font-bold text-gray-900 dark:text-white">Cookie Policy</h1>
            <p className="text-gray-600 dark:text-gray-300">Last updated: May 2025</p>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white">1. What Are Cookies</h2>
              <p className="text-gray-600 dark:text-gray-300">
                Cookies are small pieces of text sent by your web browser by a website you visit. A cookie file is stored in your web browser and allows the Service or a third-party to recognize you.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-xl font-semibold text-gray-900 dark:text-white">2. How We Use Cookies</h2>
              <p className="text-gray-600 dark:text-gray-300">
                We use cookies for the following purposes:
              </p>
              <ul className="list-disc pl-5 text-gray-600 dark:text-gray-300 space-y-1">
                <li><strong>Authentication:</strong> To identify you when you visit our website and as you navigate our website.</li>
                <li><strong>Security:</strong> To help protect user accounts, including preventing fraudulent use of login credentials.</li>
                <li><strong>Preferences:</strong> To store your preferences, such as Dark Mode settings.</li>
              </ul>
            </section>
          </div>
        );
      default:
        return <div>Content not found.</div>;
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 dark:bg-slate-900 flex flex-col font-sans transition-colors duration-200">
      {/* Header */}
      <nav className="sticky top-0 z-50 bg-white/80 dark:bg-slate-900/80 backdrop-blur-md border-b border-gray-200 dark:border-gray-800">
        <div className="max-w-7xl mx-auto w-full px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between">
          <div className="flex items-center gap-3 cursor-pointer" onClick={onBack}>
             <Logo className="w-8 h-8" />
            <span className="text-xl font-bold tracking-tight text-gray-900 dark:text-white">{APP_NAME}</span>
          </div>
          <button 
            onClick={onBack}
            className="text-sm font-medium text-gray-600 dark:text-gray-300 hover:text-medical-600 dark:hover:text-medical-400 transition-colors"
          >
            &larr; Back to Home
          </button>
        </div>
      </nav>

      {/* Content */}
      <main className="flex-1 max-w-4xl mx-auto w-full px-4 py-12 sm:px-6 lg:px-8">
        <div className="bg-white dark:bg-slate-800 rounded-2xl shadow-sm border border-gray-200 dark:border-gray-700 p-8 md:p-12">
           {renderContent()}
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-white dark:bg-slate-900 border-t border-gray-200 dark:border-gray-800 py-8">
          <div className="text-center text-sm text-gray-500 dark:text-gray-400">
            &copy; 2025 {APP_NAME}. All rights reserved.
          </div>
      </footer>
    </div>
  );
};
